services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    # لا نعرّض منفذ للخارج؛ يكفي الشبكة الداخلية
    expose:
      - "5252"
    networks:
      - appnet

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    container_name: task6-front-end
    # لا نعرّض منفذ للخارج؛ يكفي الشبكة الداخلية
    expose:
      - "9000"
    depends_on:
      - back-end
    networks:
      - appnet

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    container_name: task6-proxy
    ports:
      - "80:80"   # البروكسي فقط هو المتاح خارجيًا
    depends_on:
      - front-end
      - back-end
    networks:
      - appnet

networks:
  appnet:
